Add long description to setup.py
Building stdeb on bookworm is failing [1] on a missing long_description:

    File "/usr/lib/python3/dist-packages/stdeb/util.py", line 934, in __init__
        for line in long_description.split('\n'):
    AttributeError: 'NoneType' object has no attribute 'split'

[1]: https://app.circleci.com/pipelines/github/freedomofpress/dangerzone/484/workflows/38c579d5-b335-49ab-b56d-9539d93ef16e/jobs/2110